apiVersion: v1
kind: Service
metadata:
  name: k8sniff-ingress-lb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 8443
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
  selector:
    role: k8sniff-ingress-lb
{{- if .Values.service.externalIP }}
  externalIPs:
    - {{ .Values.service.externalIP }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}

