{{/* vim: set filetype=gotexttmpl: */ -}}
{{ if .Values.backup.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
type: Opaque
data:
{{- if eq .Values.backup.storageProvider "S3" }}
  s3-region: {{ required "missing s3 region" .Values.backup.s3.region | b64enc }}
  s3-secret-access-key: {{ required "missing s3 secret access key" .Values.backup.s3.secretAccessKey | b64enc  }}
  s3-access-key-id: {{ required "missing s3 key id" .Values.backup.s3.accessKeyID | b64enc }}
{{- else }}{{/* Swift */}}
  openstack-auth-url: {{ required "missing openstack-auth-url" .Values.openstack.authURL | b64enc }}
  openstack-username: {{ required "missing openstack-username" .Values.openstack.username | b64enc }}
  openstack-password: {{ required "missing openstack-password" .Values.openstack.password | b64enc }}
  openstack-domain-name: {{ required "missing openstack-domain-name" .Values.openstack.domainName | b64enc }}
  openstack-project-id: {{ required "missing openstack-project-id" .Values.openstack.projectID | b64enc }}
{{- end }}
{{ end -}}
