{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - name: etcd
    port: 2379
{{ if .Values.metricsProxy.enabled }}
  - name: metrics
    port: 8080
{{ end }}
  selector:
    app: {{ include "fullname" . }}
