{{ if .Values.metricsProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: metrics-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: http
  selector:
    app: metrics-proxy
{{ end }}
