# Default values for etcd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: sapcc/etcd
  tag: 3.1.12
  pullPolicy: IfNotPresent
## Persist data to a persitent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  # Re-use existing (unmanged) PVC
  # existingClaim: claimName
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
backup:
  image:
    repository: sapcc/etcdbrctl
    tag: 0.3.0
    pullPolicy: IfNotPresent
  config:
    schedule: "*/5 * * * *"
    maxBackups: 10
    deltaSnapshotPeriod: 10
    garbageCollectionPeriod: 60
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
