{{/* vim: set filetype=gotexttmpl: */ -}}
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: {{ include "master.fullname" . }}-cmanager
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.api.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ if eq (toString .Values.api.replicaCount) "1" }}0{{else}}1{{end}}
      maxSurge: 1
  selector:
    matchLabels:
      app: controller-manager
      kluster: {{ .Values.name }}
      account: {{ .Values.account }}
  template:
    metadata:
      labels:
        app: controller-manager
        kluster: {{ .Values.name }}
        account: {{ .Values.account }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: certs
          secret:
            secretName: {{ .Values.secretName }}
            items:
              - key: tls-ca.pem
                path: tls-ca.pem
              - key: apiserver-clients-system-kube-controller-manager.pem
                path: kube-client.pem
              - key: apiserver-clients-system-kube-controller-manager-key.pem
                path: kube-client.key
              - key: apiserver-nodes-ca.pem
                path: apiserver-nodes-ca.pem
              - key: apiserver-nodes-ca-key.pem
                path: apiserver-nodes-ca-key.pem
              - key: apiserver-clients-ca.pem
                path: apiserver-clients-ca.pem
              - key: apiserver-clients-ca-key.pem
                path: apiserver-clients-ca-key.pem
        - name: config
          configMap:
            name: {{ include "master.fullname" . }}
        {{- if .Values.openstack }}
        - name: cloudprovider
          secret:
            secretName: {{ include "master.fullname" . }}-generated
            items:
              - key: openstack.config
                path: openstack.config
        - name: openstack-hacks
          configMap:
            name: {{ include "master.fullname" . }}-os-hacks
        {{- end }}
        {{- if (semverCompare "< 1.13" .Values.version.kubernetes) }}
        {{- if .Values.rejectProxy.enabled }}
        - name: reject-cert-exchange
          emptyDir: {}
        {{- end }}
        {{- end }}
      initContainers:
        - name: apiserver-wait
          image: {{ include "hyperkube.image" . }}
          command:
            - /bin/sh
            - -ce
          args:
            - until kubectl cluster-info --kubeconfig /etc/kubernetes/config/kubeconfig --request-timeout=4s; do sleep 5; done;
          volumeMounts:
            - mountPath: /etc/kubernetes/certs/
              name: certs
              readOnly: true
            - mountPath: /etc/kubernetes/config
              name: config
              readOnly: true
{{ if (semverCompare "< 1.13" .Values.version.kubernetes) }}
{{ if .Values.rejectProxy.enabled }}
        - name: generate-ca
          image: "{{ .Values.rejectProxy.image.repository }}:{{ .Values.rejectProxy.image.tag }}"
          command:
            - /bin/sh
          args:
            - -ce
            - |-
              if [ ! -f /tmp/reject-cert/ca.crt ]; then
                /reject-proxy -v=true -cert-dir=/tmp/reject-cert generate-ca
              fi
          volumeMounts:
            - mountPath: /tmp/reject-cert
              name: reject-cert-exchange
      serviceAccountName: {{ include "master.fullname" . }}-reject-proxy
{{ end }}
{{ end }}
      containers:
        - name: controller-manager
          image: {{ include "hyperkube.image" . | quote }}
          command:
            - /bin/sh
          args:
            - -ce
            - |-
{{ if (semverCompare "< 1.13" .Values.version.kubernetes) }}
{{ if .Values.rejectProxy.enabled }}
              cp /tmp/reject-cert/ca.crt /usr/local/share/ca-certificates/reject-proxy-ca.crt
              update-ca-certificates
{{ end }}
{{ end }}
              exec /hyperkube \
{{- if (semverCompare ">= 1.15" .Values.version.kubernetes) }}
              kube-controller-manager \
{{- else }}
              controller-manager \
{{- end }}
              --allocate-node-cidrs=true \
            {{- if .Values.openstack }}
              --cloud-config=/etc/kubernetes/cloudprovider/openstack.config \
{{- if (semverCompare ">= 1.13" .Values.version.kubernetes) }}
              --cloud-provider=external \
              --external-cloud-volume-plugin=openstack \
{{- else }}
              --cloud-provider=openstack \
              --configure-cloud-routes=true \
{{- end }}
            {{- end }}
              --cluster-cidr={{ .Values.clusterCIDR }} \
              --cluster-name={{ .Values.name }} \
              --cluster-signing-cert-file=/etc/kubernetes/certs/apiserver-nodes-ca.pem \
              --cluster-signing-key-file=/etc/kubernetes/certs/apiserver-nodes-ca-key.pem \
              --controllers=*,bootstrapsigner,tokencleaner \
              --kubeconfig=/etc/kubernetes/config/kubeconfig \
{{- if (semverCompare ">= 1.12" .Values.version.kubernetes) }}
              --authentication-kubeconfig=/etc/kubernetes/config/kubeconfig \
              --authorization-kubeconfig=/etc/kubernetes/config/kubeconfig \
{{- end }}
{{- if (semverCompare ">= 1.14" .Values.version.kubernetes) }}
              --feature-gates=NodeLease=false \
{{- end }}
              --leader-elect=false \
              --root-ca-file=/etc/kubernetes/certs/tls-ca.pem \
              --service-account-private-key-file=/etc/kubernetes/certs/apiserver-clients-ca-key.pem \
              --service-cluster-ip-range={{ .Values.serviceCIDR }} \
              --use-service-account-credentials
{{ if (semverCompare "< 1.13" .Values.version.kubernetes) }}
{{ if .Values.rejectProxy.enabled }}
          env:
            - name: http_proxy
              value: http://127.0.0.1:8080
            - name: https_proxy
              value: http://127.0.0.1:8080
            - name: no_proxy
              value: 127.0.0.1
{{ end }}
{{ end }}
          livenessProbe:
            httpGet:
              path: /healthz
{{- if (semverCompare ">= 1.13" .Values.version.kubernetes) }}
              port: 10257
              scheme: HTTPS
{{- else }}
              port: 10252
              scheme: HTTP
{{- end }}
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - mountPath: /etc/kubernetes/certs/
              name: certs
              readOnly: true
            - mountPath: /etc/kubernetes/config
              name: config
              readOnly: true
            {{- if .Values.openstack }}
            - mountPath: /etc/kubernetes/cloudprovider
              name: cloudprovider
              readOnly: true
            - mountPath: /var/lib/cloud/data/
              name: openstack-hacks
              readOnly: true
            {{- end }}
{{ if (semverCompare "< 1.13" .Values.version.kubernetes) }}            
{{ if .Values.rejectProxy.enabled }}
            - mountPath: /tmp/reject-cert
              name: reject-cert-exchange
{{ end }}
{{ end }}
          resources:
{{ toYaml .Values.controllerManager.resources | indent 12 }}
{{ if (semverCompare "< 1.13" .Values.version.kubernetes) }}            
{{ if .Values.rejectProxy.enabled }}
        - name: reject-proxy
          command:
            - /bin/sh
          args:
            - -ce
            - |-
              /reject-proxy \
              -v=true \
              -namespace={{ .Release.Namespace }} \
              -cert-dir=/tmp/reject-cert \
              -config-map={{ include "master.fullname" . }}-reject-proxy
          image: "{{ .Values.rejectProxy.image.repository }}:{{ .Values.rejectProxy.image.tag }}"
          imagePullPolicy: {{ .Values.rejectProxy.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: reject-proxy
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp/reject-cert
              name: reject-cert-exchange
          resources:
{{ toYaml .Values.rejectProxy.resources | indent 12 }}
{{ end }}
{{ end }}
{{- if .Values.openstack }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "master.fullname" . }}-os-hacks
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
data:
  instance-id: gurkenwurst
{{- end }}
