{{ if .Values.etcd.metricsProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "master.fullname" . }}-scheduler
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 10251
  selector:
    app: {{ include "master.fullname" . }}-scheduler
{{ end }}
